version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  user-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=3003
      - MYSQL_DATABASE=user_db
    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - microservices-net

  task-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=3003
      - MYSQL_DATABASE=task_db
    ports:
      - "3308:3306"
    volumes:
      - task-db-data:/var/lib/mysql
    networks:
      - microservices-net

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=3003
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=your-very-secure-secret-key
      - JWT_EXPIRATION=86400000
    depends_on:
      - user-db
      - eureka-server
    networks:
      - microservices-net

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://task-db:3306/task_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=3003
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=your-very-secure-secret-key
    depends_on:
      - task-db
      - eureka-server
    networks:
      - microservices-net

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=your-very-secure-secret-key
    depends_on:
      - eureka-server
      - user-service
      - task-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  user-db-data:
  task-db-data:
